apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-port
    port: 9001
    targetPort: 80
    protocol: TCP
  - name: multitool-port
    port: 9002
    targetPort: 8080
    protocol: TCP

