apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
  - name: nginx-external
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP

